language: r
sudo: false
cache: packages

matrix:
  include:
  - r: devel
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
  - r: release
    os: osx
    osx_image: xcode8.3
    latex: false

r_packages:
  - covr
r_github_packages:
  - vimc/vaultr
before_script:
  - Rscript -e 'vaultr::vault_test_server_install()'
  - cp -r reference tests/testthat
  - R CMD INSTALL .
env:
  global:
    - VAULTR_TEST_SERVER_INSTALL=true
    - VAULTR_TEST_SERVER_PORT=18200
    - VAULTR_TEST_SERVER_BIN_PATH=$PWD/.vault
