language: r
sudo: false
cache: packages
r_packages:
  - covr
after_success:
  - Rscript -e 'covr::codecov()'
r_github_packages:
  - vimc/montagu-r
  - ropensci/magick
addons:
  apt:
    packages:
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev
      - libpoppler-cpp-dev
